# Generated by Django 5.0 on 2023-12-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>_1703109151.1813154', max_length=255, unique=True),
        ),
    ]
