# Generated by Django 5.0 on 2023-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(default='770a37a8-4a08-4a67-bc18-2130075c2e2b', max_length=255, unique=True),
        ),
    ]
